# This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: hugo-deploy-with-asciidoctor
      uses: cld4h/hugo-deploy@v1.2
      env:
        DEPLOY_REPO: cld4h/cld4h.github.io
        DEPLOY_BRANCH: build
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: Asia/Shanghai
